### ISSUE TITLE
I18N and L10N

### ISSUE THREAD

**Issue by mahony0** [benfreke/oc-menumanager-plugin#39]
I'm developing E-commerce system with October and using this plugin. If you can add lang folder and make texts and inputs dynamic -takes only 5-10 mins.- this plugin will be very useful. I can help editing the plugin btw. Thanks.

**Comment by benfreke** [comment]
Hi

I've not really had any time to do anything on this plugin for the last few months. It might be pretty obvious :)

But, if you make the changes on your version of the files, and do a pull request with the changes I guarantee I won't over-ride any changes you've made locally. The next version of the plugin will 100% include all pull requests. Unless they're broken of course.

**Comment by mahony0** [comment]
I updated plugin for supporting multi language. Please check for integrity, sure it's OK.

**Comment by benfreke** [comment]
Hi @mahony0 

There were some missing translations. Please have a look at the feature/1.4.0 branch for those. Or the master branch if I manage to merge everything today :)

**Comment by benfreke** [comment]
The translations are still out of date, so any pull requests will be merged if anybody has the time :)
