### ISSUE TITLE
sql error

### ISSUE THREAD

**Issue by monlone** [benfreke/oc-menumanager-plugin#43]
hi,when i add a new item to the menu.i got this error,please help,thank you!
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'internal_url' in 'field list' (SQL: insert into `benfreke_menumanager_menus` (`title`, `description`, `enabled`, `is_external`, `internal_url`, `external_url`, `link_target`, `parameters`, `query_string`, `url`, `nest_left`, `nest_right`, `updated_at`, `created_at`) values (asd, , 1, 0, , , _self, , , , 1, 2, 2015-02-21 06:46:15, 2015-02-21 06:46:15))" on line 614 of D:\xampp\htdocs\octobercms\vendor\laravel\framework\src\Illuminate\Database\Connection.php

**Comment by benfreke** [comment]
Yeah, I've fixed that but haven't had a chance to push the 1.4.0 branch as
I'm having issue with the translation part of it.

Temporary fix is to add internal_url and external_url to the purgeable
attribute on the class, and use the Purgeable trait.

Should have a fix by this time tomorrow, assuming I can figure out the
translation bug ....

**Comment by monlone** [comment]
thank you
