### ISSUE TITLE
I have error when set  Active Node to default

### ISSUE THREAD

**Issue by devillom** [benfreke/oc-menumanager-plugin#47]
I have error when set  Active Node to default

Call to a member function getBaseFileName() on a non-object
 // Go and find the page we're on
 $baseFileName = $this->page->page->getBaseFileName();

**Comment by Asinox** [comment]
Hello there, any update about this issue?

**Comment by devillom** [comment]
$baseFileName = str_replace('/','',$this->page->url);

**Comment by benfreke** [comment]
Hi @devillom , that isn't going to work as the "url" that plugin stores is not always going to match the site "url". It matches the file name instead. Which, for every page but the home page, is the same. Good times! 

Anyway, this is fixed in 1.4.3. Thanks for reporting this :)
