### ISSUE TITLE
components/Menu.php $baseFileName = $this->page->page->getBaseFileName();

### ISSUE THREAD

**Issue by fgrosswig** [benfreke/oc-menumanager-plugin#48]
Call to a member function getBaseFileName() on a non-object
$baseFileName = $this->page->page->getBaseFileName();

Depricated since Build 260 (2015-05-16)???

    The |page filter now supports passing an empty string to generate a link to the current page.
    Component variables set with $this->page no longer leech in to other component partials.

**Comment by Asinox** [comment]
Any update about it?

**Comment by benfreke** [comment]
That's a bummer. I'll have a look and see what else I can hook into for this.

**Comment by benfreke** [comment]
Fixed as part of 1.4.3. Thanks for reporting the issue :)
