### ISSUE TITLE
Menu component break on update october build 270

### ISSUE THREAD

**Issue by ribsousa** [benfreke/oc-menumanager-plugin#51]
`xception 'ErrorException' with message 'Trying to get property of non-object' in `components/Menu.php:125
`Stack trace:
`#0 

` ` `
$baseFileName = $this->page->cmsObject->page->getBaseFileName();
` ` `

**Comment by devillom** [comment]
+1

**Comment by benfreke** [comment]
PR welcome! I'm hoping to get a chance to look at it this weekend, but that's what I said last Friday too

**Comment by benfreke** [comment]
Same as 1.4.3, just stuff moved around
