### ISSUE TITLE
Reorder one menu item

### ISSUE THREAD

**Issue by paulbardack** [benfreke/oc-menumanager-plugin#54]
HI!
Thanks for your plugin.
I've reached a bug, when trying to reorder one item of the menu
"A node cannot be moved to a descendant of itself." on line 928 of /Users/bardack/www/parasport/vendor/october/rain/src/Database/Traits/NestedTree.php

**Comment by benfreke** [comment]
Closing this due to age. If it's still an issue, let me know and I'll investigate
