### ISSUE TITLE
Dropdown menu is rendered when subpage is disabled

### ISSUE THREAD

**Issue by CptMeatball** [benfreke/oc-menumanager-plugin#55]
When there is a single disabled subpage in a menu item , the dropdown menu is being rendered empty.

![screen shot 2016-01-28 at 22 38 45](https://cloud.githubusercontent.com/assets/1681727/12659591/e90bbdd6-c60f-11e5-9114-b50ff8aa26af.png)

**Comment by benfreke** [comment]
The plugin doesn't check the status of the pages. It definitely should, and at the same time menus should have that ability. Definitely useful.
