### ISSUE TITLE
Menu is not appearing on the frontend

### ISSUE THREAD

**Issue by worldofsmarty** [benfreke/oc-menumanager-plugin#56]
I have added the menu to a page and configured all the menu links from a menu tab. The menu is not appearing on the webpage. What may be the issue.

**Comment by lzodevelopment** [comment]
same problem here

**Comment by austinderrick** [comment]
Try adding it from the CMS area instead of hard coding in the template. It seems to require some of the settings there, so you can't simply add the component to the template.

**Comment by 69alberich** [comment]
i have the same problem, any ideas?

**Comment by benfreke** [comment]
For me, if I added the component in the code directly it didn't work. It needed to be added through the CMS, and also required you to click on the component to bring up the options. That seems to trigger something to make it work.

If someone can provide some repeatable steps, please re-open and I'll investigate.
