### ISSUE TITLE
The reserved indicator "@" cannot start a plain scalar

### ISSUE THREAD

**Issue by jcorapi** [benfreke/oc-menumanager-plugin#57]
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 9 (near "form: @/plugins/benfreke/menumanager/models/menu/fields.yaml").
/home/pooperpumper/public_html/vendor/symfony/yaml/Inline.php line 259

**Comment by worldofsmarty** [comment]
I am also receiving the same error. Kindly resolve this error as soon as possible. Thank you.

**Comment by mrbohnke** [comment]
This can be easily by solved by ourselves (developer fix would be totally appreciated, though)
locating **config_form.yaml** and **config_list.yaml**
(at **/benfreke/menumanager/controllers/menus/**)
and replacing
`@/plugins/benfreke/menumanager/`
for
`$/benfreke/menumanager/`
Also, in **Menus.php** (at **/benfreke/menumanager/controllers/**), line 34:
`$this->addJs('/plugins/benfreke/menumanager/assets/js/benfreke.menumanager.js');`
for
`$this->addJs('/benfreke/menumanager/assets/js/benfreke.menumanager.js');`
and, on line 70:
`$toolbarConfig->buttons = '@/plugins/benfreke/menumanager/controllers/menus/_reorder_toolbar.htm';`
for
`$toolbarConfig->buttons = '$/benfreke/menumanager/controllers/menus/_reorder_toolbar.htm';`

**Comment by 69alberich** [comment]
@mrbohnke thx dude! it works

**Comment by jacktoothill** [comment]
@mrbohnke perfect!

**Comment by jacktoothill** [comment]
Hi @mrbohnke,

I have just tried reordering a menu and ran in to the following error:

Creating default object from empty value
/var/www/public/plugins/benfreke/menumanager/controllers/menus.php line 69

it is highlighting the line changed in menus.php:
$toolbarConfig->buttons = '$/benfreke/menumanager/controllers/menus/_reorder_toolbar.htm';

Any ideas how to resolve this?

Thanks

**Comment by jacktoothill** [comment]
Never mind, I deleted a line by mistake.

**Comment by benfreke** [comment]
I've merged some Pull Requests. They didn't have the change to the JS though, and when I load the backend the JS is still loaded correctly. I'm closing this as it appears to be fixed. If not, please re-open.

Thanks :)
