### ISSUE TITLE
Reorder_toolbar not found.

### ISSUE THREAD

**Issue by CptMeatball** [benfreke/oc-menumanager-plugin#66]
In Controller `menus.php` the `reorder` method looks for:

`~/benfreke/menumanager/controllers/menus/_reorder_toolbar.htm`
See: https://github.com/benfreke/oc-menumanager-plugin/blob/master/controllers/Menus.php#L70

This causes following error:

![screen shot 2016-11-21 at 17 15 02](https://cloud.githubusercontent.com/assets/1681727/20490380/1dc9d6fa-b00e-11e6-963e-2a4f335d3461.png)

**Comment by davemof** [comment]
The error is on line 70 of:

benfreke/menumanger/controllers/Menus.php

change line to:

$toolbarConfig->buttons = '~/plugins/benfreke/menumanager/controllers/menus/_reorder_toolbar.htm';

and it should work then
