### ISSUE TITLE
multiple menus

### ISSUE THREAD

**Issue by littlegreenguy** [benfreke/oc-menumanager-plugin#79]
I can't see a way of adding multiple menus - can I add this as a feature request??

Thanks!

**Comment by benfreke** [comment]
Hi littlegreenguy

That feature is already built in. Have a re-read of the instructions on using this, specifically selecting the parent node. The menu manager will contain every node within the menu, to display these as different menus within the site select a different parent node for each menu.

https://octobercms.com/plugin/benfreke-menumanager#documentation

**Comment by littlegreenguy** [comment]
Perfect! Apologies for missing that.

Thanks very much for getting back to me,

Nick
