### ISSUE TITLE
How to make menu appear on mobile dropdown navigation menu?

### ISSUE THREAD

**Issue by SalmanRavoof** [benfreke/oc-menumanager-plugin#82]
I created two new menu items with this plugin. It's working perfectly on the desktop site. 

However, those new menus are not visible on mobiles and tablets. How do I fix that?

**Comment by benfreke** [comment]
No idea sorry, that's a css issue with your theme. 

If you need extra classes the functionality is there to do so. 

If you have more information then please reopen, but if the html is on the page then this is working as designed.
