### ISSUE TITLE
Menu is not show on the theme

### ISSUE THREAD

**Issue by ardyanto** [benfreke/oc-menumanager-plugin#89]
I have added the menu to a page and configured all the menu links from a menu tab. The menu is not appearing on the webpage

and i dump {{ dump(parentNode.getChildren) }} but the value is null (0)

please help me ..thank you

**Comment by benfreke** [comment]
Hi @ardyanto 

What does the menu structure look like in the admin? What is the parent node selected on the component? Have you followed the instructions here: https://octobercms.com/plugin/benfreke-menumanager#documentation ?

Most issues are related to not understanding the requirement around parent nodes.

**Comment by ardyanto** [comment]
hi @benfreke 

my structure  menu in admin
- HOME
- CONTACT US
- SERVICE
- ETC

and I add menu in layout 

{% component "menu" %}

but menu not show

**Comment by ardyanto** [comment]
ok solved..thank you
