### ISSUE TITLE
Do not create Controller instance every time getLinkHref is called

### ISSUE THREAD

**Issue by Pepelac** [benfreke/oc-menumanager-plugin#91]
Hi,

is there any reason of not doing this
```
$this->controller = BaseController::getController() ?? new BaseController();
```
instead of this?
https://github.com/benfreke/oc-menumanager-plugin/blob/9467eda95354a8d31ff45a7c0fc34d380ee8e8d0/models/Menu.php#L165

Now it creates router instance (and other stuff) every time `\BenFreke\MenuManager\Models\Menu::getLinkHref` is called.

**Comment by benfreke** [comment]
Hi

1) The `??` operator is only available from PHP 7, and when this code was written it needed to work in PHP56. That line was added nearly 5 years ago.
2) It's not good.

Better code would be to instantiate the `$this->controller` in the construct method.

You're right though. This is bad code and if I had any tests when I wrote this 5 years ago I would have hopefully picked this up.
