### ISSUE TITLE
How to list `Static Pages` 

### ISSUE THREAD

**Issue by mittultechnobrave** [benfreke/oc-menumanager-plugin#92]
How can i list the pages which I created as `Static Page` which I created from Static Pages plugin (https://octobercms.com/plugin/rainlab-pages) ? 

I want to show it `File to link to` dropdown options when I select `Internal` from `Menu Type` dropdown. Currently its only showing `CMS` pages in the list. 

Is it possible ?

**Comment by benfreke** [comment]
Hi

It's not possible as it is writen now sorry.

But looking at that plugin, it already has menus built in, so I wouldn't be using this plugin to create menus.
